/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChart: typeof import('primevue/chart')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeFileUpload: typeof import('primevue/fileupload')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimePaginator: typeof import('primevue/paginator')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeProgressSpinner: typeof import('primevue/progressspinner')['default']
    PrimeRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeSplitButton: typeof import('primevue/splitbutton')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabView: typeof import('primevue/tabview')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
