/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admins.index"];
        put?: never;
        post: operations["admins.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/admins/{admin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admins.show"];
        put: operations["admins.update"];
        post?: never;
        delete: operations["admins.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/activity-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminActivityLog.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cartItem.index"];
        put?: never;
        post: operations["cartItem.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{cartItem}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cartItem.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories.index"];
        put?: never;
        post: operations["categories.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories.show"];
        put: operations["categories.update"];
        post?: never;
        delete: operations["categories.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{category}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categoryPrice.index"];
        put?: never;
        post: operations["categoryPrice.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clientProfile.show_0"];
        put: operations["clientProfile.update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/client-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client-profiles.index"];
        put?: never;
        post: operations["client-profiles.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/client-profiles/{clientProfile}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client-profiles.show"];
        put: operations["client-profiles.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invoices.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{invoice}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invoices.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leads.index"];
        put?: never;
        post: operations["leads.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/leads/{lead}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leads.show"];
        put: operations["leads.update"];
        post?: never;
        delete: operations["leads.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lead-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lead-sales.index"];
        put?: never;
        post: operations["lead-sales.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lead-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lead-sources.index"];
        put?: never;
        post: operations["lead-sources.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lead-sources/{leadSource}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lead-sources.show"];
        put: operations["lead-sources.update"];
        post?: never;
        delete: operations["lead-sources.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notificationSetting.index"];
        put: operations["notificationSetting.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order.index_0"];
        put?: never;
        post: operations["order.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order.show_0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_order.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_order.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{order}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orderItem.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["packages.index"];
        put?: never;
        post: operations["packages.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/packages/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["packages.show"];
        put: operations["packages.update"];
        post?: never;
        delete: operations["packages.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["provinces.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/provinces/{province}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["provinces.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicCatalog.leads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicCatalog.categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicCatalog.provinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/lead-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publicLeadSubmission.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["systemSetting.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system-settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["systemSetting.show"];
        put: operations["systemSetting.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions/{transaction}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.show"];
        put: operations["users.update"];
        post?: never;
        delete: operations["users.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["userLead.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-leads/{userLead}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["userLead.show"];
        put: operations["userLead.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["userPackage.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-packages/{userPackage}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["userPackage.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionMode
         * @enum {string}
         */
        AcquisitionMode: "exclusive" | "shared" | "free";
        /**
         * AcquisitionType
         * @enum {string}
         */
        AcquisitionType: "exclusive" | "shared" | "free_trial";
        /** Admin */
        Admin: {
            id: number;
            email: string;
            first_name: string;
            last_name: string;
            role: components["schemas"]["AdminRole"];
            status: components["schemas"]["AdminStatus"];
            /** Format: date-time */
            last_login_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * AdminRole
         * @enum {string}
         */
        AdminRole: "super_admin" | "admin" | "operator";
        /**
         * AdminStatus
         * @enum {string}
         */
        AdminStatus: "active" | "inactive";
        /** CartItem */
        CartItem: {
            id: number;
            user_id: number;
            lead_id: number;
            purchase_mode: components["schemas"]["PurchaseMode"];
            price: string;
            /** Format: date-time */
            added_at: string;
        };
        /** Category */
        Category: {
            id: number;
            name: string;
            slug: string;
            description: string | null;
            max_shares: number;
            is_active: boolean;
            sort_order: number;
            custom_fields: unknown[] | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
        };
        /** CategoryPrice */
        CategoryPrice: {
            id: number;
            category_id: number;
            exclusive_price: string;
            shared_prices: unknown[];
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** ClientProfile */
        ClientProfile: {
            id: number;
            user_id: number;
            company_name: string;
            vat_number: string;
            phone: string;
            first_name: string;
            last_name: string;
            billing_address: string;
            billing_city: string;
            billing_province: string;
            billing_zip: string;
            billing_country: string;
            sdi_code: string | null;
            pec_email: string | null;
            free_trial_enabled: boolean;
            free_trial_leads_remaining: number;
            email_notifications_enabled: boolean;
            marketing_consent: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * ContactStatus
         * @enum {string}
         */
        ContactStatus: "new" | "contacted" | "in_progress" | "not_interested" | "converted" | "unreachable";
        /** Invoice */
        Invoice: {
            id: number;
            order_id: number;
            invoice_number: string;
            type: components["schemas"]["InvoiceType"];
            fatture_cloud_id: string | null;
            sdi_status: components["schemas"]["SdiStatus"];
            sdi_message: string | null;
            subtotal: string;
            vat_rate: string;
            vat_amount: string;
            total: string;
            billing_data: unknown[] | null;
            notes: string | null;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            due_at: string | null;
            /** Format: date-time */
            sent_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * InvoiceType
         * @enum {string}
         */
        InvoiceType: "invoice" | "credit_note";
        /** Lead */
        Lead: {
            id: number;
            category_id: number;
            province_id: number;
            source_id: number;
            first_name: string;
            last_name: string;
            email: string;
            phone: string;
            request_text: string;
            extra_tags: unknown[] | null;
            status: components["schemas"]["LeadStatus"];
            current_shares: number;
            /** Format: date-time */
            generated_at: string;
            external_id: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** LeadSale */
        LeadSale: {
            id: number;
            lead_id: number;
            user_id: number;
            order_id: number | null;
            user_package_id: number | null;
            mode: components["schemas"]["AcquisitionMode"];
            share_slot: number | null;
            price_paid: string;
            /** Format: date-time */
            sold_at: string;
        };
        /** LeadSource */
        LeadSource: {
            id: number;
            name: string;
            slug: string;
            description: string | null;
            is_active: boolean;
            config: unknown[] | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * LeadStatus
         * @enum {string}
         */
        LeadStatus: "free" | "sold_exclusive" | "sold_shared" | "exhausted";
        /** LengthAwarePaginator */
        LengthAwarePaginator: unknown[];
        /**
         * NotificationFrequency
         * @enum {string}
         */
        NotificationFrequency: "instant" | "hourly" | "daily" | "weekly" | "disabled";
        /** NotificationSetting */
        NotificationSetting: {
            id: number;
            user_id: number;
            category_id: number;
            category_name: string;
            frequency: components["schemas"]["NotificationFrequency"];
            enabled: boolean;
        };
        /** Order */
        Order: {
            id: number;
            user_id: number;
            order_number: string;
            type: components["schemas"]["OrderType"];
            payment_method: components["schemas"]["PaymentMethod"];
            subtotal: string;
            vat_rate: string;
            vat_amount: string;
            total: string;
            status: components["schemas"]["OrderStatus"];
            billing_snapshot: unknown[] | null;
            invoice_number: string | null;
            invoice_url: string | null;
            payment_id: string | null;
            /** Format: date-time */
            paid_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** OrderItem */
        OrderItem: {
            id: number;
            order_id: number;
            lead_id: number | null;
            package_id: number | null;
            acquisition_mode: components["schemas"]["AcquisitionMode"];
            unit_price: string;
            quantity: number;
            line_total: string;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "processing" | "paid" | "completed" | "failed" | "refunded" | "cancelled";
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "single" | "package" | "free_trial";
        /** Package */
        Package: {
            id: number;
            category_ids: unknown[];
            name: string;
            description: string | null;
            exclusive_lead_quantity: number;
            exclusive_price: string;
            shared_lead_quantity: number;
            shared_price: string;
            is_active: boolean;
            sort_order: number;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * PackageStatus
         * @enum {string}
         */
        PackageStatus: "active" | "exhausted" | "expired";
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "card" | "sepa" | "free";
        /** Province */
        Province: {
            id: number;
            name: string;
            code: string;
            region: string;
            is_active: boolean;
        };
        /**
         * PurchaseMode
         * @enum {string}
         */
        PurchaseMode: "exclusive" | "shared";
        /**
         * SdiStatus
         * @enum {string}
         */
        SdiStatus: "pending" | "sent" | "delivered" | "accepted" | "rejected" | "not_delivered" | "error";
        /** SystemSetting */
        SystemSetting: {
            id: number;
            key: string;
            value: unknown[];
            description: string | null;
        };
        /** Transaction */
        Transaction: {
            id: number;
            order_id: number;
            stripe_payment_intent_id: string | null;
            stripe_charge_id: string | null;
            stripe_customer_id: string | null;
            stripe_payment_method_id: string | null;
            payment_type: components["schemas"]["TransactionPaymentType"];
            amount: string;
            currency: string;
            status: components["schemas"]["TransactionStatus"];
            metadata: unknown[] | null;
            failure_code: string | null;
            failure_message: string | null;
            /** Format: date-time */
            processed_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * TransactionPaymentType
         * @enum {string}
         */
        TransactionPaymentType: "card" | "sepa_debit";
        /**
         * TransactionStatus
         * @enum {string}
         */
        TransactionStatus: "pending" | "requires_action" | "processing" | "succeeded" | "failed" | "canceled";
        /** User */
        User: {
            id: number;
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** UserLead */
        UserLead: {
            id: number;
            user_id: number;
            lead_id: number;
            order_id: number | null;
            acquisition_type: components["schemas"]["AcquisitionType"];
            purchase_price: string;
            contact_status: components["schemas"]["ContactStatus"];
            notes: string | null;
            /** Format: date-time */
            purchased_at: string;
            /** Format: date-time */
            last_contacted_at: string | null;
        };
        /** UserPackage */
        UserPackage: {
            id: number;
            user_id: number;
            package_id: number;
            order_id: number;
            package_name: string;
            category_id: number | null;
            total_leads: number;
            exclusive_leads_total: number;
            exclusive_leads_used: number;
            shared_leads_total: number;
            shared_leads_used: number;
            status: components["schemas"]["PackageStatus"];
            /** Format: date-time */
            purchased_at: string;
            /** Format: date-time */
            expires_at: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "client" | "admin" | "super_admin";
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "pending" | "active" | "suspended" | "blocked";
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admins.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "admins.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    first_name: string;
                    last_name: string;
                    password: string;
                    role: string;
                    status?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        admin: components["schemas"]["Admin"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "admins.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The admin ID */
                admin: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        admin: components["schemas"]["Admin"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "admins.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The admin ID */
                admin: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string;
                    first_name?: string;
                    last_name?: string;
                    password?: string;
                    role?: string;
                    status?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        admin: components["schemas"]["Admin"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "admins.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The admin ID */
                admin: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "adminActivityLog.index": {
        parameters: {
            query?: {
                admin_id?: string;
                type?: string;
                entity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    password_confirmation: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Registration successful. Please verify your email.";
                        user: components["schemas"]["User"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        user: components["schemas"]["User"];
                        token: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Password reset logic will be implemented with notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "If the email exists, a password reset link has been sent.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password reset logic will be implemented with tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Password has been reset successfully.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out successfully.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "cartItem.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cart_items: components["schemas"]["CartItem"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "cartItem.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lead_id: number;
                    purchase_mode: string;
                    price: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cart_item: components["schemas"]["CartItem"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cartItem.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The cart item ID */
                cartItem: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "categories.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories: components["schemas"]["Category"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "categories.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    description?: string | null;
                    max_shares?: number;
                    is_active?: boolean;
                    sort_order?: number;
                    custom_fields?: string[] | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category: components["schemas"]["Category"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "categories.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category: components["schemas"]["Category"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "categories.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    slug?: string;
                    description?: string | null;
                    max_shares?: number;
                    is_active?: boolean;
                    sort_order?: number;
                    custom_fields?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category: components["schemas"]["Category"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "categories.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Soft delete
             *
             *
             *
             *     No content
             */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "categoryPrice.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        prices: components["schemas"]["CategoryPrice"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "categoryPrice.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    exclusive_price: number;
                    shared_prices: string[];
                    /** Format: date-time */
                    valid_from: string;
                    /** Format: date-time */
                    valid_to?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        price: components["schemas"]["CategoryPrice"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "clientProfile.show_0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_profile: components["schemas"]["ClientProfile"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "clientProfile.update_1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    company_name?: string;
                    vat_number?: string;
                    phone?: string | null;
                    first_name?: string;
                    last_name?: string;
                    billing_address?: string | null;
                    billing_city?: string | null;
                    billing_province?: string | null;
                    billing_zip?: string | null;
                    billing_country?: string | null;
                    sdi_code?: string | null;
                    /** Format: email */
                    pec_email?: string | null;
                    email_notifications_enabled?: boolean;
                    marketing_consent?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_profile: components["schemas"]["ClientProfile"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client-profiles.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client-profiles.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_id: number;
                    company_name: string;
                    vat_number: string;
                    phone?: string | null;
                    first_name: string;
                    last_name: string;
                    billing_address?: string | null;
                    billing_city?: string | null;
                    billing_province?: string | null;
                    billing_zip?: string | null;
                    billing_country?: string | null;
                    sdi_code?: string | null;
                    /** Format: email */
                    pec_email?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_profile: components["schemas"]["ClientProfile"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client-profiles.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientProfile: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_profile: components["schemas"]["ClientProfile"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client-profiles.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientProfile: string | null;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    company_name?: string;
                    vat_number?: string;
                    phone?: string | null;
                    first_name?: string;
                    last_name?: string;
                    billing_address?: string | null;
                    billing_city?: string | null;
                    billing_province?: string | null;
                    billing_zip?: string | null;
                    billing_country?: string | null;
                    sdi_code?: string | null;
                    /** Format: email */
                    pec_email?: string | null;
                    email_notifications_enabled?: boolean;
                    marketing_consent?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_profile: components["schemas"]["ClientProfile"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "invoices.index": {
        parameters: {
            query?: {
                sdi_status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "invoices.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The invoice ID */
                invoice: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invoice: components["schemas"]["Invoice"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "leads.index": {
        parameters: {
            query?: {
                category_id?: string;
                province_id?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "leads.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_id: number;
                    province_id: number;
                    source_id: number;
                    first_name: string;
                    last_name: string;
                    /** Format: email */
                    email: string;
                    phone: string;
                    request_text: string;
                    extra_tags?: string[] | null;
                    /** Format: date-time */
                    generated_at?: string;
                    external_id?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead: components["schemas"]["Lead"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "leads.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead: components["schemas"]["Lead"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "leads.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    category_id?: number;
                    province_id?: number;
                    source_id?: number;
                    first_name?: string;
                    last_name?: string;
                    /** Format: email */
                    email?: string;
                    phone?: string;
                    request_text?: string;
                    extra_tags?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead: components["schemas"]["Lead"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "leads.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Cannot delete a lead that has been sold.";
                    };
                };
            };
        };
    };
    "lead-sales.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lead-sales.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lead_id: number;
                    user_id: number;
                    order_id?: number | null;
                    user_package_id?: number | null;
                    mode: string;
                    share_slot?: number | null;
                    price_paid: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead_sale: components["schemas"]["LeadSale"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lead-sources.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lead-sources.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    description?: string | null;
                    api_key?: string | null;
                    is_active?: boolean;
                    config?: string[] | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead_source: components["schemas"]["LeadSource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lead-sources.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead source ID */
                leadSource: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead_source: components["schemas"]["LeadSource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lead-sources.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead source ID */
                leadSource: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    slug?: string;
                    description?: string | null;
                    api_key?: string | null;
                    is_active?: boolean;
                    config?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lead_source: components["schemas"]["LeadSource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lead-sources.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead source ID */
                leadSource: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "notificationSetting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notification_settings: components["schemas"]["NotificationSetting"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notificationSetting.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    settings: {
                        category_id: number;
                        frequency: string;
                        enabled: boolean;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notification_settings: components["schemas"]["NotificationSetting"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "order.index_0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "order.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: string;
                    payment_method: string;
                    items: {
                        lead_id?: number | null;
                        package_id?: number | null;
                        acquisition_mode?: string | null;
                        unit_price: number;
                        quantity: number;
                    }[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "order.show_0": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "admin_order.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "admin_order.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "orderItem.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderItem"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "packages.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "packages.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string | null;
                    exclusive_lead_quantity: number;
                    exclusive_price: number;
                    shared_lead_quantity: number;
                    shared_price: number;
                    is_active?: boolean;
                    sort_order?: number;
                    category_ids: number[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        package: components["schemas"]["Package"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "packages.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        package: components["schemas"]["Package"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "packages.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                    exclusive_lead_quantity?: number;
                    exclusive_price?: number;
                    shared_lead_quantity?: number;
                    shared_price?: number;
                    is_active?: boolean;
                    sort_order?: number;
                    category_ids?: number[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        package: components["schemas"]["Package"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "packages.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "provinces.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        provinces: components["schemas"]["Province"][];
                    } | {
                        provinces: string[][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "provinces.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The province ID */
                province: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        province: components["schemas"]["Province"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "publicCatalog.leads": {
        parameters: {
            query?: {
                category_id?: string;
                province_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            category: components["schemas"]["Category"];
                            province: components["schemas"]["Province"];
                            request_preview: string;
                            generated_at: string;
                            status: components["schemas"]["LeadStatus"];
                            current_shares: number;
                        }[];
                        current_page: number;
                        last_page: number;
                        per_page: number;
                        total: number;
                    };
                };
            };
        };
    };
    "publicCatalog.categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    "publicCatalog.provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        provinces: components["schemas"]["Province"][];
                    };
                };
            };
        };
    };
    "publicLeadSubmission.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_slug: string;
                    province_id?: number | null;
                    first_name: string;
                    last_name: string;
                    /** Format: email */
                    email: string;
                    phone: string;
                    request_text: string;
                    extra_tags?: string[] | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Lead submitted successfully.";
                        lead_id: number;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "systemSetting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settings: components["schemas"]["SystemSetting"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "systemSetting.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        setting: components["schemas"]["SystemSetting"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "systemSetting.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        setting: components["schemas"]["SystemSetting"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "transactions.index": {
        parameters: {
            query?: {
                status?: string;
                payment_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "transactions.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The transaction ID */
                transaction: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transaction: components["schemas"]["Transaction"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "users.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string;
                    role?: string;
                    status?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "users.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "userLead.index": {
        parameters: {
            query?: {
                contact_status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LengthAwarePaginator"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "userLead.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user lead ID */
                userLead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_lead: components["schemas"]["UserLead"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "userLead.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user lead ID */
                userLead: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    contact_status?: string;
                    notes?: string | null;
                    /** Format: date-time */
                    last_contacted_at?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_lead: components["schemas"]["UserLead"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "userPackage.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_packages: components["schemas"]["UserPackage"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "userPackage.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user package ID */
                userPackage: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_package: components["schemas"]["UserPackage"];
                        usage_stats: {
                            exclusive_remaining: string;
                            shared_remaining: string;
                            total_remaining: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
